name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Lint
        run: uv sync && make lint
  test:
    runs-on: "${{ matrix.OS }}"
    strategy:
      matrix:
        OS: [ubuntu-24.04, windows-2022, macos-14]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Test by tox
        run: make tox
  db_test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: uv sync --all-groups
      - name: Setup KeePassXC
        run: .\ci\setup-keepassxc.ps1
      - name: Test
        run: |
          # Launch KeePassXC
          &'C:\Program Files\KeePassXC\KeePassXC.exe' --config .\tests\data\keepassxc.ini --keyfile .\tests\data\test_db.keyx .\tests\data\test_db.kdbx
          Start-Sleep -Seconds 5
          # Test
          uv run pytest tests -v --cov=src --cov-branch --cov-report=term --cov-report=html
